import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import { GetStaticPaths, GetStaticProps } from "next";
import { fetchPosts } from "@services/contentful";
import { extractPathsFormated } from "src/utils/formating";

const Post: NextPage = ({ post }: any) => {
  return (
    <div className="container">
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,600;1,400;1,600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header>
        <h1 className="blog-post-title">{post.title}</h1>
      </header>

      <main className="main">
        <div className="media-md">
          <div className="hero">
            <Image
              src={`https:${post.hero.url}`}
              alt={post.hero.alt}
              layout="fill"
            />
          </div>
          <div className="meta-data-md">
            <div className="meta-md">
              <span className="meta-title-state">Published</span>
              <span className="meta-content-state">{post.date}</span>
            </div>
            <div className="meta-md">
              <span className="meta-title-state">Author</span>
              <span className="meta-content-blue-state">{post.author}</span>
            </div>
            <div className="meta-md">
              <span className="meta-title-state">Category</span>
              <span className="meta-content-blue-state">{post.category}</span>
            </div>
          </div>
        </div>
        <div
          className="body-md"
          dangerouslySetInnerHTML={{ __html: post.body }}
        />
      </main>
      <style jsx>{`
        .container {
          display: flex;
          flex-direction: column;
          margin-left: 6em;
          width: 100%;
        }
        .hero {
          position: relative;
          width: 45em;
          height: 24em;
        }
        .media-md {
          display: flex;
        }
        .meta-data-md {
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          height: 12em;
          margin-left: 2em;
        }
        .meta-md {
          display: flex;
          flex-direction: column;
        }
        .body-md {
          width: 45em;
        }
        .meta-title-state {
          text-transform: uppercase;
          margin-bottom: 1em;
        }
        .meta-content-state {
          font-weight: 200;
        }
        .meta-content-blue-state {
          color: rgb(11, 106, 230);
        }
      `}</style>
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const posts = await fetchPosts();
  const paths = extractPathsFormated(posts);
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }: any) => {
  const posts = await fetchPosts();
  const post = posts.find((element) => element.slug === params.slug);

  return {
    props: { post: post },
  };
};

export default Post;
