import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BlogSection from "components/BlogSection/BlogSection";
import { getPosts } from "@services/contentful";

const Home: NextPage = (props: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contentful blog by Mike</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogSection variant="featured" posts={props.posts} />
      <BlogSection title="MOST POPULAR" variant="grid" posts={props.posts} />
      <BlogSection title="BROWSE ALL" variant="grid" posts={props.posts} />
      <main className={styles.main}></main>
    </div>
  );
};

export async function getServerSideProps() {
  let items;
  items = await getPosts();
  return { props: { posts: items || null } };
}

export default Home;
